# .github/workflows/firebase-hosting-pr.yml
# Deploy a preview version of the Vite site on every PR
# Project root layout:
#   vite-project/
#     ├─ package.json
#     ├─ package-lock.json
#     ├─ firebase.json
#     └─ (etc.)

name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build_and_preview:
    # Skip PRs that come from forks (no secrets there)
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

    runs-on: ubuntu-latest

    # All run: commands execute inside vite-project/
    defaults:
      run:
        working-directory: ./vite-project

    steps:
      # 1 – checkout code
      - uses: actions/checkout@v4

      # 2 – consistent Node version + npm cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./vite-project/package-lock.json

      # 3 – install & build
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build          # must exist in vite-project/package.json

      # 4 – deploy to a short-lived preview channel
      - name: Deploy preview to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken:              ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ONO_CAFETERIA }}
          projectId:              ono-cafeteria
          entryPoint:             ./vite-project        # where firebase.json lives
          channelId:              pr-${{ github.event.pull_request.number }}
          expires:                7d                    # auto-delete after 7 days
