# .github/workflows/firebase-hosting-merge.yml
# Generated for a Vite project located in ./vite-project

name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # All “run:” commands inherit this working directory
    defaults:
      run:
        working-directory: ./vite-project

    steps:
      # 1 — checkout source
      - uses: actions/checkout@v4

      # 2 — set up Node (cache speeds up ci)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20          # choose the version you use locally
          cache: npm                # caches ~/.npm
          cache-dependency-path: ./vite-project/package-lock.json

      # 3 — install & build
      - name: Install dependencies
        run: npm ci                 # uses package-lock.json in vite-project/

      - name: Build
        run: npm run build          # must exist in vite-project/package.json

      # 4 — deploy the dist/ folder generated by Vite
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken:              ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ONO_CAFETERIA }}
          projectId:              ono-cafeteria
          channelId:              live
          entryPoint:             ./vite-project   # where firebase.json lives
